
=head1 Boostrapping the Client Environment

This document will discuss how to bootstrap the EFS client
environment, once the server environment has been successfully
bootstrapped.

=head1 Initial Requirements

If it's not yet obvious, you have to complete the procedures
documented in "Bootstrapping the Server Environment".  This process is
similar, but far simpler.

=head2 EFS Compile Hosts

The EFS administrators, and any team who will be building content for
/efs/dist for that matter, needs to have access to at least one client
for each platform you wish to support in your environment.  Although
additional client platforms can certainly be added at a later date, it
is orders of magnitude more complex to accomplish once the environment
has been completely bootstrapped, and especially after you have
deployed prod cells and clients.

Note that these machines will be used to compile platform-specific
content for /efs, and they will in general NOT be used as EFS servers.
Having said that, it is prefectly reasonable to use the initial EFS
server to satisfy the requirement for one of the platforms, but once
the EFS domain goes "live", the EFS server should be used exclusively
for efsd.   

=head1 Configuring the Bootstrap Process

This process will use the exact same configuration file that you wrote
for bootstrapping the server environment. 

=head1 Installing the EFS Software

On each of the client hosts, we will go through a two step process to
get the EFS distribution compiled into /efs/dist/efs/core.  First, the
EFS client configured and started, and then the source code is
compiled into /efs/dist directly.

These steps must be performed on each of the client hosts, in the
following order.  

=head2 efs_bootstrap_client

This script will configure and start the EFS client, making the
/efs/dev and /efs/dist namespaces available locally.  To run this
script, you will need to invoke the script from the root directory of
the source tree, and you will also need to make sure that the
source/bin directory is in your $PATH, since some of the scripts
included in the distribution will be run for you.  These scripts:

    efs_platform
    efs_configure_autofs
    rc.efs

were all designed to be run without first requiring installation, so
they can be run directly from the source tree as part of this process.

    cd /path/to/source
    PATH=./bin:$PATH
    ./util/efs_configure_client -config /path/to/bootstrap.conf

See the efs_configure_client man page for additional details on
running this script.

    cd /path/to/source
    pod2text < doc/efs_bootstrap_client.pod | less

This must be run as root, since it creates NFS mounts, alters the
autofs configuration, and manages the autofs process.

=head2 efs_bootstrap_install

This script will automatically choose:

    /efs/dist/efs/core/bootstrap/.exec/$platform

as the prefix for installation, if that directory is present.  When
the server bootstrapping process is complete, those directories are
pre-created to aid the client bootstrapping process.

This invocation must be run as a non-root user, who is a member of the
efsops UNIX group.  The clients (in this case, the "compile hosts")
will normally not have root access to the EFS NFS shares.  Only the
EFS servers (the machines intended to run efsd) should have such
access.

To invoke this script:

    cd /path/to/source
    ./util/efs_bootstrap_install -config /path/to/bootstrap.conf

You should already be familiar with this script, since you used it to
bootstrap the server infrastructure first.

=cut
