
=head1 Debugging EFS

=head2 Debugging efsd in the test.efs environment

In order to debug efsd in the test.efs setup, you have to run the test
suite through at least the 00_setup scripts, and depending on what you
intend to debug, the 05_startup scripts as well.

Debugging efsd is a two step process. First, you have to run efsd in
the debugger and set the appropriate break point of interest, and then
in a separate shell you run the client to initiate the efsd operation.

Credentials can be manually acquired using the following command:

    kinit -k -t /var/kerberos/keytabs/efsops.keytab efsops

Even if you're running the AFS enabled version of the EFS test suite,
you don't need AFS tokens, just the basic krb5 credentials for
client/server authentication.

Then, run the efs client as follows, where we're assuming the the
current working directory is the EFS source tree you're trying to
debug.

    perl -Mblib bin/efs checkpoint release $m $p $r --serverhost $(hostname -f)

This should connect to the efsd you have running in the debugger, as
described above.  You should be back at the debugging prompt at the
beginning of the function where the breakpoint was set.

=head2 Debugging efsd in a deployed release

TBD

=cut
